### PR TITLE
Make UI Stream Proof

### PR DESCRIPTION
**Pull request by louga31**
This is a little change to the hook of the D3D_PRESENT_FUNCTION function to make it Stream Proof.
I just hook the Steam hooked version of D3D_PRESENT_FUNCTION, so streaming softwares like OBS think the cheat UI is part of Steam Overlay and ignore it.

### CODE REVIEW

**Comment by WooAf** [comment]
Work pretty good

**Comment by manianac** [comment]
I like it.  I added a sigscan for present, and a fallback with warning to the user.

**Comment by manianac** [comment]
Alright, lets get some tests in with these latest changes and see what everyone thinks.

**Comment by louga31** [comment]
Okay, let's see.
If you need help for tests, don't hesitate to ask.

**Comment by Keirou** [comment]
How to test the streamproof version??
unsure how to compile DLL's (new to all this)

**Comment by OsOmE1** [comment]
I suggest you google it you’ll be surprised how much information is on there.

**Pull request merged**
